### ISSUE TITLE
Requirements not correct in CanonHero  game example

### ISSUE THREAD

**Issue by rameshakula** [GameAutomators/eBook-Source#62]
Why Sudoku Game should be installed in Mobile Phone in Canon Hero game example

**Comment by psurya1994** [comment]
Thanks for letting us know! 

@karthikshathiri: can you please fix this and see if we have similar problems in any of the other games?

**Comment by karthikshathiri** [comment]
Done.

**Comment by sudheesh001** [comment]
Fixed via merge b3777c06d7f022c1408ff9073280979f7a2f66e8
